"""add progress

Revision ID: 70d9c8dd39bb
Revises: 
Create Date: 2021-08-11 21:55:56.907902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d9c8dd39bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('video_name', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('status', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=False),
    sa.Column('faces_count', sa.Integer(), nullable=False),
    sa.Column('is_delete', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
